# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
x = torch.rand(size=(7,7))
x, x.shape

(tensor([[8.2775e-01, 7.8372e-01, 2.6239e-01, 2.8270e-01, 4.2482e-01, 6.8933e-04,
          1.6366e-01],
         [4.9180e-01, 7.9268e-01, 7.7313e-01, 4.8420e-01, 2.4637e-01, 3.3611e-01,
          5.3484e-01],
         [9.5954e-02, 9.1421e-01, 3.2022e-01, 2.7017e-01, 2.3204e-01, 4.0592e-02,
          3.8762e-01],
         [3.5438e-01, 5.3870e-01, 6.5136e-01, 5.1060e-01, 5.3525e-01, 8.2965e-01,
          5.7549e-01],
         [1.7418e-01, 3.9926e-01, 8.4187e-01, 9.8789e-02, 9.0665e-02, 5.6574e-01,
          6.5275e-01],
         [9.8412e-01, 5.0192e-01, 2.5722e-01, 4.2592e-01, 3.7653e-01, 1.1261e-01,
          9.1661e-01],
         [3.1311e-01, 9.0942e-01, 1.3646e-01, 9.1610e-01, 6.7822e-01, 7.4789e-02,
          6.2167e-01]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
y = torch.rand(size=(1,7))
# Perform matrix multiplication 
z = x @ y.T
z, z.shape

(tensor([[1.6066],
         [1.8706],
         [1.2530],
         [1.9279],
         [1.2364],
         [1.8927],
         [1.9825]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x = torch.rand(size=(7,7))
y = torch.rand(size=(1,7))

# Matrix multiply tensors
z = x @ y.T

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
x = torch.rand(size=(2,3)).to(device)
y = torch.rand(size=(2,3)).to(device)

device, x, y

('cuda',
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
z = x @ y.T
z, z.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
max_val = torch.max(z)
# Find min
min_val = torch.min(z)

max_val, min_val

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
max_idx = torch.argmax(z)

# Find arg min
min_idx = torch.argmin(z)

max_idx, min_idx

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
x = torch.rand(size=(1,1,1,10))
y = x.squeeze()

# Remove single dimensions


# Print out tensors and their shapes
x, x.shape, y, y.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))